package com.elmaanum.hermit;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        new RDF4J().queryRemoteRepos("string", "string", "string");
    }
}
